name: SSH deploy by github action to ubuntu

on:
  push:
    branches: [ deploy ]
  # pull_request:
  #   branches: [ master ]

jobs:
  # This workflow contains a single job called "ssh_deploy"
  ssh_deploy:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2
    # - name: Install Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '10.x'
    # - name: Install yarn
    #   run:  npm install yarn

    # - name: Install npm dependencies
    #   run:  yarn install
      
    # - name: Run build task
    #   run:  yarn run build --if-present

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host:     ${{ secrets.LOCAL }}
        username: ${{ secrets.REMOTE_USER }}
        key:      ${{ secrets.SERVER_SSH_KEY }}
        port:     ${{ secrets.SSH_PORT }}
        script: |
          ls -la
          cd react && git pull origin deploy
          yarn run build
